# Generated by Django 3.2.6 on 2021-08-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_surname', models.CharField(db_index=True, max_length=255)),
                ('passport_number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcodes', models.ImageField(upload_to=255)),
                ('which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yeah.students')),
            ],
        ),
    ]
