# Generated by Django 3.2.6 on 2021-08-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='qrcodes',
            field=models.ImageField(upload_to='static/QrCodes/'),
        ),
    ]
