# Generated by Django 3.2.9 on 2021-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeah', '0003_students_student_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='student_token',
        ),
        migrations.AddField(
            model_name='qrcodes',
            name='student_token',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
